- name: Verify MySQL connection using telnet
  hosts: webservers_cf, webservers_tf
  gather_facts: false
  become: yes
  tasks:
    - name: Install telnet
      ansible.builtin.shell: yum install -y telnet
    
    - name: Check MySQL connection to db-server-cf
      wait_for:
        host: "{{ item }}"
        port: 3306
        timeout: 6
      ignore_errors: true
      register: mysql_conn_status
      loop: "{{ groups['dbservers'] }}"
      

    - name: Display connection status
      debug:
        msg: |
          Connection status to db-servers:
          {{ 'SUCCESS' if mysql_conn_status is success else 'FAILED' }}

         