---
- name: Reset MySQL root password
  hosts: dbservers-cf
  become: yes
  gather_facts: no

  tasks:
    - name: Stop MySQL service
      service:
        name: mysql
        state: stopped

    - name: Start MySQL in safe mode
      command: mysqld_safe --skip-grant-tables
      async: 0
      poll: 0
      ignore_errors: yes

    - name: Wait for MySQL to start in safe mode
      wait_for:
        port: 3306
        delay: 5
        timeout: 300

    - name: Set new MySQL root password
      mysql_user:
        name: root
        password: "{{ task-12-password }}"
        host: dbservers-cf
        state: present

    - name: Flush privileges
      mysql_user:
        name: root
        login_user: root
        login_password: ""
        host: dbservers-cf
        state: present
        priv: "*.*:ALL,GRANT"
        append_privs: yes

    - name: Stop MySQL in safe mode
      shell: pkill -f "mysqld_safe --skip-grant-tables"
      ignore_errors: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started

  vars:
    mysql_root_password: "new_mysql_root_password"
