---
- name: Add EC2 instance public IDs to inventory
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ec2_region: "eu-central-1"  # Modify with your desired region
    ec2_instance_tags:
      - Key: "Project"  # Modify with your desired tag key
        Values:
          - "task-12"  # Modify with your desired tag value
    inventory_path: "~/task-12/ansible_playbooks/inventory/prod.ini"  # Modify with your desired inventory path

  tasks:
    - name: Get EC2 instance public IDs
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
            "tag:Key": "Project"
            "tag:Value": "task-12"
        profile: "aleksIaC"
      register: ec2_instances

    - name: Add EC2 instance public IDs to inventory file
      lineinfile:
        path: "{{ inventory_path }}"
        line: "{{ item.public_ip_address }}"
      loop: "{{ ec2_instances.instances }}"
